//
//  SecondHandView.swift
//  Lifespan 2018
//
//  Created by John Pavley on 2/22/18.
//  Copyright © 2018 jpavley12. All rights reserved.
//

import UIKit

class SecondHandView: CoreGraphicsView {
    
    let secondHandPathRef = CGMutablePath()
    
    // Only override draw() if you perform custom drawing.
    // An empty implementation adversely affects performance during animation.
    override func draw(_ rect: CGRect) {
        // Drawing code
        
        drawSecondHand()
        self.transform = CGAffineTransform(rotationAngle: CGFloat(angle).degreesToRadians)

    }
    
    
    /// Code generated by Graphics.app.
    private func drawSecondHand() {
        guard let ctx = UIGraphicsGetCurrentContext() else { return }
        // enable the following lines for flipped coordinate systems
        // ctx.translateBy(x: 0, y: self.bounds.size.height)
        // ctx.scaleBy(x: 1, y: -1)
        
        let scaleFactor: CGFloat = calcScaleFactor(viewWidth: self.bounds.width)
        ctx.scaleBy(x: scaleFactor, y: scaleFactor)
        
        /*  Shape   */
        secondHandPathRef.move(to: CGPoint(x: 314.679, y: 367.873))
        secondHandPathRef.addCurve(to: CGPoint(x: 314.679, y: 329.796), control1: CGPoint(x: 314.679, y: 367.873), control2: CGPoint(x: 314.679, y: 329.796))
        secondHandPathRef.addCurve(to: CGPoint(x: 318.226, y: 323.45), control1: CGPoint(x: 314.679, y: 329.796), control2: CGPoint(x: 318.226, y: 323.45))
        secondHandPathRef.addCurve(to: CGPoint(x: 318.226, y: 317.104), control1: CGPoint(x: 318.226, y: 323.45), control2: CGPoint(x: 318.226, y: 317.104))
        secondHandPathRef.addCurve(to: CGPoint(x: 314.679, y: 310.758), control1: CGPoint(x: 318.226, y: 317.104), control2: CGPoint(x: 314.679, y: 310.758))
        secondHandPathRef.addCurve(to: CGPoint(x: 318.226, y: 158.449), control1: CGPoint(x: 314.679, y: 310.758), control2: CGPoint(x: 318.226, y: 158.449))
        secondHandPathRef.addCurve(to: CGPoint(x: 321.774, y: 158.449), control1: CGPoint(x: 318.226, y: 158.449), control2: CGPoint(x: 321.774, y: 158.449))
        secondHandPathRef.addCurve(to: CGPoint(x: 325.321, y: 310.758), control1: CGPoint(x: 321.774, y: 158.449), control2: CGPoint(x: 325.321, y: 310.758))
        secondHandPathRef.addCurve(to: CGPoint(x: 321.774, y: 317.104), control1: CGPoint(x: 325.321, y: 310.758), control2: CGPoint(x: 321.774, y: 317.104))
        secondHandPathRef.addCurve(to: CGPoint(x: 321.774, y: 323.45), control1: CGPoint(x: 321.774, y: 317.104), control2: CGPoint(x: 321.774, y: 323.45))
        secondHandPathRef.addCurve(to: CGPoint(x: 325.321, y: 329.796), control1: CGPoint(x: 321.774, y: 323.45), control2: CGPoint(x: 325.321, y: 329.796))
        secondHandPathRef.addCurve(to: CGPoint(x: 325.321, y: 367.873), control1: CGPoint(x: 325.321, y: 329.796), control2: CGPoint(x: 325.321, y: 367.873))
        secondHandPathRef.addCurve(to: CGPoint(x: 314.679, y: 367.873), control1: CGPoint(x: 325.321, y: 367.873), control2: CGPoint(x: 314.679, y: 367.873))
        secondHandPathRef.closeSubpath()
        
        ctx.setFillColor(red: 0.671, green: 0.082, blue: 0, alpha: 1)
        ctx.addPath(secondHandPathRef)
        ctx.fillPath()
    }

}
